# Generated by Django 6.0.5 on 2026-06-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_order_updated_alter_order_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="content",
            new_name="comment",
        ),
    ]
