# Generated by Django 6.0.5 on 2026-06-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "ትዕዛዝ ላይ ያለ (Pending)"),
                    ("Shipped", "የተላከ (Shipped)"),
                    ("Delivered", "ደረሰ (Delivered)"),
                    ("Canceled", "የተሰረዘ (Canceled)"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
